version: "3.9"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - db
    logging:
      driver: none

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: celery -A ipno.config worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - redis
      - db
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
    logging:
      driver: none

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python ipno/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
      - redis
    networks:
      - elasticsearch
      - db
      - redis

volumes:
  esdata:

networks:
  elasticsearch:
    driver: bridge
  db:
    driver: bridge
  redis:
    driver: bridge