version: "3.9"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - db
    logging:
      driver: none

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elasticsearch
    logging:
      driver: none

  web:
    build: .
    command: "gunicorn config.wsgi -c gunicorn-logging.conf.py --chdir /code/ipno"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      FLUENT_LOGGING: "True"
    volumes:
      - .:/code
      - log-folder:/var/log
    ports:
      - "8000:8000"
    depends_on:
      - db
      - fluent-bit
    networks:
      - elasticsearch
      - db

  fluent-bit:
    build:
      context: .
      dockerfile: fluent-bit/Dockerfile.fluent
    command: "/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf"
    ports:
        - "24224:24224/tcp"
        - "24224:24224/udp"
    volumes:
      - ./fluent-bit:/fluent-bit/etc/
      - log-folder:/var/log

volumes:
  esdata:
  log-folder:

networks:
  elasticsearch:
    driver: bridge
  db:
    driver: bridge