version: "3.9"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - db
    logging:
      driver: none

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
    logging:
      driver: none

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python ipno/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    networks:
      - elasticsearch
      - db

volumes:
  esdata:

networks:
  elasticsearch:
    driver: bridge
  db:
    driver: bridge